[package]
name = "introbot"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bimap = "0.6.2"
serenity = "0.11"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-subscriber = "0.2"
