# fly.toml file generated for introbot on 2023-02-07T19:50:07+09:00

app = "introbot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  processes = ["introbot"]
  script_checks = []
